# Generated by Django 2.0.1 on 2020-02-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200219_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='tappuser',
            name='has_realname',
            field=models.IntegerField(choices=[(0, '未实名认证'), (1, '已实名认真')], default=0, verbose_name='实名状态'),
        ),
    ]
